export const supportedLanguages = [
  { code: 'en', label: 'English', browserCodes: ['en'] },
  { code: 'sv', label: 'Svenska', browserCodes: ['sv'] },
  { code: 'no', label: 'Norsk', browserCodes: ['no', 'nb', 'nn'] },
  { code: 'fi', label: 'Suomi', browserCodes: ['fi'] },
  { code: 'da', label: 'Dansk', browserCodes: ['da'] },
  { code: 'is', label: 'Íslenska', browserCodes: ['is'] },
] as const;

export const localeContent = {
  en: {
    title: 'Viking Bio Integration',
    metaDescription: 'Viking Bio integration for monitoring and managing pellet burner telemetry with a Pico-based bridge and local configurator.',
    brandAria: 'Viking Bio home',
    nav: ['Overview', 'Features', 'Architecture', 'Project'],
    heroEyebrow: 'Pellet burner monitoring',
    heroTitle: 'Turn a Viking Bio 20 into a connected, observable heating system',
    heroLead: 'This project brings together a Raspberry Pi Pico bridge, signed telemetry, and a local Go configurator to monitor burner health, track operational state, and simplify setup on a home or property network.',
    ctaExplore: 'Explore the project',
    ctaSource: 'View source',
    overviewEyebrow: 'Overview',
    overviewTitle: 'Built for reliability, visibility, and local ownership',
    featureTelemetryTitle: 'Signed telemetry',
    featureTelemetryBody: 'Each message is authenticated with a device key so the local server can verify incoming burner data.',
    featureUSBTitle: 'USB provisioning',
    featureUSBBody: 'Bridge setup can happen over serial with a GUI or terminal-based configurator, making installation straightforward.',
    featureNetworkTitle: 'Browser notifications',
    featureNetworkBody: 'The runtime is built around a local-first model: the Go service exposes APIs and USB setup, while the separate push-pwa app handles browser notifications for burner alerts and reminders.',
    featureMDNSTitle: 'mDNS discovery',
    featureMDNSBody: 'The bridge listens for mDNS announcements from the configurator, allowing automatic service discovery on a home network without manual configuration.',
    featureStateTitle: 'Persistent state',
    featureStateBody: 'Wi‑Fi credentials, server settings, and per-device identity are kept in local flash-backed storage.',
    featureHardwareTitle: 'Open hardware path',
    featureHardwareBody: 'The repo is intentionally transparent: firmware, protocol parsing, runtime, and configuration tooling live together.',
    architectureEyebrow: 'Architecture',
    architectureTitle: 'Simple layered flow, clear ownership, and a local-first runtime',
    architectureBody: 'The system separates the hardware-facing bridge from the Go runtime and the separate browser-push app. The Pico reads burner data and streams signed telemetry to a Go process on the same trusted local network. That Go process exposes the API and USB configuration flow while the bridge stays focused on measurement, ingest, and alert delivery.',
    architectureSteps: ['Burner serial data', 'Pico W / Pico 2 W firmware', 'Signed TCP ingest', 'Go runtime + local APIs', 'Browser notifications'],
    projectEyebrow: 'Project',
    projectTitle: 'Built for owners, integrators, and makers who want a practical burner monitor',
    projectBody1: 'This repository is a complete integration project for the Viking Bio 20 pellet burner: firmware, protocol parsing, local runtime, and a separate browser push app for operator alerts. It is designed to be understandable, extensible, and easy to run on a small local device or home network.',
    projectBody2: 'The focus is honest operational control: keep data local, verify the device at the edge, and provide a reliable configuration flow without depending on a hosted product or cloud backend.',
    footerBrand: 'Viking Bio Integration',
    footerGitHub: 'GitHub',
    widget: {
      setup: 'Local setup',
      bridge: 'Bridge',
      online: 'Online',
      telemetry: 'Telemetry',
      signed: 'Signed',
      config: 'Config',
      ready: 'Ready',
      wifi: 'Wi‑Fi',
      stable: 'Stable',
      fan: 'Fan',
      flame: 'Flame',
      healthy: 'Healthy',
      state: 'State',
      idle: 'Idle',
    },
  },
  sv: {
    title: 'Viking Bio Integration',
    metaDescription: 'Viking Bio-integration för att övervaka och hantera telemetri från pelletsbrännare med en Pico-baserad brygga och lokal konfigurator.',
    brandAria: 'Viking Bio startsida',
    nav: ['Översikt', 'Funktioner', 'Arkitektur', 'Projekt'],
    heroEyebrow: 'Pellettbrännarmonitorering',
    heroTitle: 'Gör en Viking Bio 20 till ett uppkopplat, observerbart värmesystem',
    heroLead: 'Det här projektet kombinerar en Raspberry Pi Pico-brygga, signerad telemetri och en lokal Go-konfigurator för att övervaka brännarens hälsa, följa driftstatus och förenkla installation i hemmet eller på fastigheten.',
    ctaExplore: 'Utforska projektet',
    ctaSource: 'Visa källkod',
    overviewEyebrow: 'Översikt',
    overviewTitle: 'Byggt för tillförlitlighet, överblick och lokalt ägarskap',
    featureTelemetryTitle: 'Signerad telemetri',
    featureTelemetryBody: 'Varje meddelande autentiseras med en enhetsnyckel så att den lokala servern kan verifiera inkommande data.',
    featureUSBTitle: 'USB-installation',
    featureUSBBody: 'Bryggkonfiguration kan ske över seriell port med GUI eller terminalbaserad konfigurator, vilket gör installationen enkel.',
    featureNetworkTitle: 'Lokal runtime med skrivbordsapp + terminalsetup',
    featureNetworkBody: 'Runtime är byggt kring en lokal, enhetscentrerad modell: Go-tjänsten exponeras via API och USB-konfiguration, medan browser-notifieringar hanteras av den separata push-pwa-appen.',
    featureMDNSTitle: 'mDNS-upptäckt',
    featureMDNSBody: 'Bryggan lyssnar efter mDNS-meddelanden från konfiguratorn, vilket möjliggör automatisk tjänsteupptäckt i ett hemnät utan manuell konfiguration.',
    featureStateTitle: 'Beständig status',
    featureStateBody: 'Wi‑Fi-uppgifter, serverinställningar och per-enhetsidentifiering sparas i lokal flash-baserad lagring.',
    featureHardwareTitle: 'Öppen hårdvaruväg',
    featureHardwareBody: 'Repo:t är avsiktligt transparent: firmware, protokollparsering, runtime och konfigurationsverktyg finns samlat.',
    architectureEyebrow: 'Arkitektur',
    architectureTitle: 'Enkelt lagerflöde, tydlig ansvarsfördelning och lokal-first design',
    architectureBody: 'Systemet separerar hårdvarunära bryggan från den Go-runtimen och den separata browser-push-appen. Pico läser brännardata och strömmar signerad telemetri till en Go-process i samma lokala nätverk. Den processen exponeras via API och USB-konfigurationsflöde medan bryggan fokuserar på mätning, ingest och varningstillförsel.',
    architectureSteps: ['Brännarens seriedata', 'Pico W / Pico 2 W-firmware', 'Signerad TCP-ingest', 'Go runtime + lokalt API', 'Browser-notifieringar'],
    projectEyebrow: 'Projekt',
    projectTitle: 'Byggt för ägare, installatörer och skapare som vill ha en praktisk brännarmonitor',
    projectBody1: 'Det här repo:t är ett komplett integrationsprojekt för Viking Bio 20-pelletbrännaren: firmware, protokollanalys, lokal runtime och en separat browser-push-app för operatörsvarningar. Det är designat för att vara lätt att förstå, utöka och köra på liten lokal utrustning i hemmet.',
    projectBody2: 'Fokus ligger på ärlig driftkontroll: håll data lokalt, verifiera enheten i kanten och erbjuda ett pålitligt konfigurationsflöde utan att vara beroende av en hostad produkt eller molnbackend.',
    footerBrand: 'Viking Bio Integration',
    footerGitHub: 'GitHub',
    widget: {
      setup: 'Lokal installation',
      bridge: 'Brygga',
      online: 'Online',
      telemetry: 'Telemetri',
      signed: 'Signerad',
      config: 'Konfig',
      ready: 'Klar',
      wifi: 'Wi‑Fi',
      stable: 'Stabil',
      fan: 'Fläkt',
      flame: 'Låga',
      healthy: 'Frisk',
      state: 'Tillstånd',
      idle: 'Inaktiv',
    },
  },
  no: {
    title: 'Viking Bio Integration',
    metaDescription: 'Viking Bio-integrasjon for å overvåke og administrere pelletbrenseltelemetri med en Pico-basert bro og lokal konfigurasjon.',
    brandAria: 'Viking Bio startside',
    nav: ['Oversikt', 'Funksjoner', 'Arkitektur', 'Prosjekt'],
    heroEyebrow: 'Overvåkning av pelletfyr',
    heroTitle: 'Gjør en Viking Bio 20 til et koblet, observerbart varmesystem',
    heroLead: 'Dette prosjektet kombinerer en Raspberry Pi Pico-bro, signert telemetri og en lokal Go-konfigurator for å overvåke brennerens helse, spore driftstilstand og forenkle oppsett på hjemmenettverk eller eiendom.',
    ctaExplore: 'Utforsk prosjektet',
    ctaSource: 'Vis kildekode',
    overviewEyebrow: 'Oversikt',
    overviewTitle: 'Bygget for pålitelighet, synlighet og lokalt eierskap',
    featureTelemetryTitle: 'Signert telemetri',
    featureTelemetryBody: 'Hver melding er autentisert med en enhetsnøkkel, slik at den lokale tjeneren kan verifisere innkommende brennerdata.',
    featureUSBTitle: 'USB-oppsett',
    featureUSBBody: 'Brooppsett kan skje over seriell port med GUI eller terminalbasert konfigurasjon, noe som gjør installasjonen enkel.',
    featureNetworkTitle: 'Lokal runtime med skrivebordsapp + terminaloppsett',
    featureNetworkBody: 'Runtime er bygget rundt en lokal, enhetsorientert modell: Go-tjenesten eksponerer API-er og USB-oppsett, mens den separate push-pwa-appen håndterer nettlesernotifikasjoner for brennervarsler og påminnelser.',
    featureMDNSTitle: 'mDNS-oppdagelse',
    featureMDNSBody: 'Broen lytter etter mDNS-varsler fra konfigurasjonen, som muliggjør automatisk tjenesteoppdagelse på hjemmenettverk uten manuell konfigurasjon.',
    featureStateTitle: 'Vedvarende tilstand',
    featureStateBody: 'Wi‑Fi-opplysninger, tjenerinnstillinger og per-enhet-identitet lagres i lokal flash-basert lagring.',
    featureHardwareTitle: 'Åpen maskinvarevei',
    featureHardwareBody: 'Repoet er bevisst gjennomsiktig: firmware, protokollanalyse, runtime og konfigurasjonsverktøy lever sammen.',
    architectureEyebrow: 'Arkitektur',
    architectureTitle: 'Enkelt lagdelt flyt, tydelig eierskap og lokal-first runtime',
    architectureBody: 'Systemet skiller hardvarenas bro fra Go-runtimeen og den separate browser-push-appen. Pico leser brennerdata og sender signert telemetri til en Go-prosess i samme tillitsfulle lokale nettverk. Den prosessen eksponerer API-er og USB-konfigurasjonsflyt, mens broen holder fokus på måling, ingest og varsling.',
    architectureSteps: ['Brenner seriedata', 'Pico W / Pico 2 W-firmware', 'Signert TCP-ingest', 'Go runtime + lokale API-er', 'Nettlesernotifikasjoner'],
    projectEyebrow: 'Prosjekt',
    projectTitle: 'Bygget for eiere, integratorer og skapere som vil ha en praktisk brennermonitor',
    projectBody1: 'Dette repoet er et komplett integrasjonsprosjekt for Viking Bio 20-pelletbrenneren: firmware, protokollanalyse, lokal runtime og en separat browser-push-app for operatørvarsler. Det er designet for å være forståelig, utvidbart og enkelt å kjøre på liten lokal enhet eller hjemmenettverk.',
    projectBody2: 'Fokuset er ærlig operasjonell kontroll: hold data lokalt, verifiser enheten i kanten og gi et pålitelig konfigurasjonsflyt uten å være avhengig av en vertet produkt eller cloud-backend.',
    footerBrand: 'Viking Bio Integration',
    footerGitHub: 'GitHub',
    widget: {
      setup: 'Lokal oppsett',
      bridge: 'Bro',
      online: 'Tilkoblet',
      telemetry: 'Telemetri',
      signed: 'Signert',
      config: 'Konfig',
      ready: 'Klar',
      wifi: 'Wi‑Fi',
      stable: 'Stabil',
      fan: 'Vifte',
      flame: 'Flamme',
      healthy: 'Sunn',
      state: 'Tilstand',
      idle: 'Inaktiv',
    },
  },
  fi: {
    title: 'Viking Bio Integration',
    metaDescription: 'Viking Bio -integraatio pellettikattilan telemetrian seurantaan ja hallintaan Pico-pohjaisella sillalla ja paikallisella konfiguraattorilla.',
    brandAria: 'Viking Bio etusivu',
    nav: ['Yleiskatsaus', 'Ominaisuudet', 'Arkkitehtuuri', 'Projekti'],
    heroEyebrow: 'Pellettikattilan seuranta',
    heroTitle: 'Muuta Viking Bio 20 yhdistettyyn, havainnoitavaan lämmitysjärjestelmään',
    heroLead: 'Tämä projekti yhdistää Raspberry Pi Pico -sillan, allekirjoitetun telemetrian ja paikallisen Go-konfiguraattorin, jotta kattilan terveys, käyttötila ja asennus voidaan seurata kotiverkossa tai kiinteistöllä.',
    ctaExplore: 'Tutustu projektiin',
    ctaSource: 'Näytä lähdekoodi',
    overviewEyebrow: 'Yleiskatsaus',
    overviewTitle: 'Rakennettu luotettavuudelle, näkyvyydelle ja paikalliselle omistajuudelle',
    featureTelemetryTitle: 'Allekirjoitettu telemetria',
    featureTelemetryBody: 'Jokainen viesti on autentisoitu laiteavaimella, jotta paikallinen palvelin voi vahvistaa tulevan kattiladatan.',
    featureUSBTitle: 'USB-asennus',
    featureUSBBody: 'Silta voidaan konfiguroida sarjaportin kautta GUI- tai terminaalipohjaisella konfiguraattorilla.',
    featureNetworkTitle: 'Paikallinen runtime + työpöytäsovellus',
    featureNetworkBody: 'Runtime on rakennettu paikalliseen lähestymistapaan: Go-palvelu paljastaa API:t ja USB-asennuksen, kun taas erillinen push-pwa-sovellus käsittelee selaimen ilmoituksia.',
    featureMDNSTitle: 'mDNS-löytö',
    featureMDNSBody: 'Silta kuuntelee konfiguraattorin mDNS-ilmoituksia, jolloin palvelun automaattinen havaitseminen on mahdollista kotiverkossa ilman manuaalista asetusta.',
    featureStateTitle: 'Pysyvä tila',
    featureStateBody: 'Wi‑Fi-tiedot, palvelinasetukset ja laittekohtainen identiteetti tallennetaan paikalliseen flash-pohjaiseen tilaan.',
    featureHardwareTitle: 'Avoin laitteistopolku',
    featureHardwareBody: 'Repo on tarkoituksella läpinäkyvä: firmware, protokollaparserointi, runtime ja konfigurointityökalut elävät yhdessä.',
    architectureEyebrow: 'Arkkitehtuuri',
    architectureTitle: 'Yksinkertainen kerroksittainen virta ja paikallinen ensisijainen runtime',
    architectureBody: 'Järjestelmä erottaa laitteiston puoleisen sillan Go-runtimesta ja erillisestä selaimen push-sovelluksesta. Pico lukee kattilan dataa ja lähettää allekirjoitettua telemetriaa Go-prosessiin samassa luotetussa lähiverkossa.',
    architectureSteps: ['Kattilan sarjadata', 'Pico W / Pico 2 W -firmware', 'Allekirjoitettu TCP-ingest', 'Go runtime + paikalliset API:t', 'Selaimen ilmoitukset'],
    projectEyebrow: 'Projekti',
    projectTitle: 'Rakennettu omistajille, integraattoreille ja tekijöille, jotka haluavat käytännöllisen kattilanseurannan',
    projectBody1: 'Tämä repositorio on täydellinen integraatioprojekti Viking Bio 20 -pellettikattilalle: firmware, protokollaparsing, paikallinen runtime ja erillinen browser push -sovellus operaattoreille.',
    projectBody2: 'Painopiste on rehellinen operatiivinen kontrolli: pidä data paikallisesti, vahvista laite reunassa ja tarjoa luotettava asennusvirta ilman isännöityä tuotetta tai pilvipalvelua.',
    footerBrand: 'Viking Bio Integration',
    footerGitHub: 'GitHub',
    widget: {
      setup: 'Paikallinen asennus',
      bridge: 'Silta',
      online: 'Online',
      telemetry: 'Telemetria',
      signed: 'Allekirjoitettu',
      config: 'Konfiguraatio',
      ready: 'Valmis',
      wifi: 'Wi‑Fi',
      stable: 'Vakaa',
      fan: 'Tuuletin',
      flame: 'Liekki',
      healthy: 'Terve',
      state: 'Tila',
      idle: 'Leppoisa',
    },
  },
  da: {
    title: 'Viking Bio Integration',
    metaDescription: 'Viking Bio-integration til overvågning og styring af pelletbrændertelemetri med en Pico-baseret bro og lokal konfigurator.',
    brandAria: 'Viking Bio hjemmeside',
    nav: ['Oversigt', 'Funktioner', 'Arkitektur', 'Projekt'],
    heroEyebrow: 'Overvågning af pelletbrænder',
    heroTitle: 'Gør en Viking Bio 20 til et forbundet, observerbart varmesystem',
    heroLead: 'Dette projekt kombinerer en Raspberry Pi Pico-bro, signeret telemetri og en lokal Go-konfigurator for at overvåge brænderens sundhed og status på hjemmenetværk eller ejendom.',
    ctaExplore: 'Udforsk projektet',
    ctaSource: 'Vis kildekode',
    overviewEyebrow: 'Oversigt',
    overviewTitle: 'Bygget til pålidelighed, synlighed og lokalt ejerskab',
    featureTelemetryTitle: 'Signeret telemetri',
    featureTelemetryBody: 'Hver meddelelse er autentificeret med en enhedsnøgle, så den lokale server kan verificere indkommende brænderdata.',
    featureUSBTitle: 'USB-opsætning',
    featureUSBBody: 'Broopsætning kan ske over seriel port med GUI eller terminalbaseret konfigurationsværktøj.',
    featureNetworkTitle: 'Lokal runtime + desktop-app',
    featureNetworkBody: 'Runtime er bygget omkring en lokal, enhedsfokuseret model: Go-tjenesten eksponerer API-er og USB-oppsætning, mens den separate push-pwa-app håndterer browsernotifikationer.',
    featureMDNSTitle: 'mDNS-opdagelse',
    featureMDNSBody: 'Broen lytter efter mDNS-meddelelser fra konfigurationsværktøjet, hvilket gør automatisk tjenesteopdagelse muligt uden manuel konfiguration.',
    featureStateTitle: 'Vedvarende tilstand',
    featureStateBody: 'Wi‑Fi-oplysninger, serverindstillinger og per-enhed-identitet gemmes i lokal flash-baseret lagring.',
    featureHardwareTitle: 'Åben hardware-vej',
    featureHardwareBody: 'Repoet er bevidst gennemsigtigt: firmware, protokolparsing, runtime og konfigurationsværktøjer lever sammen.',
    architectureEyebrow: 'Arkitektur',
    architectureTitle: 'Simpel lagdelt flow, tydeligt ejerskab og local-first runtime',
    architectureBody: 'Systemet adskiller hardware-tilknyttede broen fra Go-runtimeen og den separate browser-push-app. Pico læser brænderdata og sender signeret telemetri til en Go-proces i samme lokale netværk.',
    architectureSteps: ['Brænderens seriedata', 'Pico W / Pico 2 W firmware', 'Signeret TCP-ingest', 'Go runtime + lokale API-er', 'Browsernotifikationer'],
    projectEyebrow: 'Projekt',
    projectTitle: 'Bygget til ejere, integratorer og skabere, der vil have en praktisk brændermonitor',
    projectBody1: 'Dette repo er et komplet integrationsprojekt til Viking Bio 20 pelletbrænderen: firmware, protokolparsing, lokal runtime og en separat browser-push-app til operatørvarsler.',
    projectBody2: 'Fokus er ærlig driftkontrol: hold data lokalt, verificer enheden i kanten og giv en pålidelig konfigurationsflow uden afhængighed af en hostet produkt eller cloud-backend.',
    footerBrand: 'Viking Bio Integration',
    footerGitHub: 'GitHub',
    widget: {
      setup: 'Lokal opsætning',
      bridge: 'Bro',
      online: 'Online',
      telemetry: 'Telemetri',
      signed: 'Signeret',
      config: 'Konfig',
      ready: 'Klar',
      wifi: 'Wi‑Fi',
      stable: 'Stabil',
      fan: 'Blæser',
      flame: 'Flamme',
      healthy: 'Sund',
      state: 'Tilstand',
      idle: 'Inaktiv',
    },
  },
  is: {
    title: 'Viking Bio Integration',
    metaDescription: 'Viking Bio-samþætting til eftirlit og stjórnun á kornofntelemetríu með Pico-undirstaða brú og staðbundnum stillingarhjálp.',
    brandAria: 'Viking Bio forsíða',
    nav: ['Yfirlit', 'Eiginleikar', 'Skipulag', 'Verkefni'],
    heroEyebrow: 'Eftirlit með kornofni',
    heroTitle: 'Gerðu Viking Bio 20 að tengdu, greinanlegu upphitunarkerfi',
    heroLead: 'Þetta verkefni sameinar Raspberry Pi Pico-brú, undirritaða telemetríu og staðbundna Go-stillingarhjálp til að fylgjast með heilsu ofns, rekstrarstöðu og einfaldari uppsetningu á heimavél eða eign.',
    ctaExplore: 'Skoða verkefnið',
    ctaSource: 'Sjá kóða',
    overviewEyebrow: 'Yfirlit',
    overviewTitle: 'Byggt fyrir áreiðanleika, sýnileika og staðbundið eignarhald',
    featureTelemetryTitle: 'Undirrituð telemetría',
    featureTelemetryBody: 'Hver skilaboð eru auðkennd með tæki lykli, svo staðbundinn þjónn geti staðfest innkomandi gögn.',
    featureUSBTitle: 'USB-uppsetning',
    featureUSBBody: 'Brúaruppsetning getur farið fram yfir raðtengi með GUI eða skel-jafnvægi stillingarhjálp.',
    featureNetworkTitle: 'Staðbundin runtime + skjáborðsforrit',
    featureNetworkBody: 'Runtime er byggt á staðbundnu, tæki-fókusuðu líkani: Go-þjónustan sýnir API og USB-uppsetningu, en aðskilin push-pwa app sér um vafra tilkynningar.',
    featureMDNSTitle: 'mDNS-uppgötvun',
    featureMDNSBody: 'Brúin hlustar eftir mDNS-tilkynningum frá stillingarhjálpinni, sem gerir sjálfvirka þjónustuleit mögulega án handvirkrar stillingar.',
    featureStateTitle: 'Fastur ástand',
    featureStateBody: 'Wi‑Fi-gögn, netþjónsstillingar og hvert tæki er vistað í staðbundinni flash-lagningu.',
    featureHardwareTitle: 'Opinn vélbúnaðarleið',
    featureHardwareBody: 'Git-repoið er viljandi gegnsætt: firmware, samskiptargreining, runtime og stillingarverkfæri lifa saman.',
    architectureEyebrow: 'Skipulag',
    architectureTitle: 'Einfalt lögskipt flæði, skýr eiginleiki og staðbundið runtime',
    architectureBody: 'Kerfið aðskilur vélbúnaðarnálga brúna frá Go-runtime og sérstöku browser-push appinu. Pico les inn gögn og streymir undirritaðri telemetríu til Go-ferlis á sama trausta staðbundna neti.',
    architectureSteps: ['Raðgögn ofns', 'Pico W / Pico 2 W firmware', 'Undirrituð TCP-ingest', 'Go runtime + staðbundin API', 'Vafra tilkynningar'],
    projectEyebrow: 'Verkefni',
    projectTitle: 'Byggt fyrir eigendur, samþættingaraðila og skaparar sem vilja hagnýta ofnsvöktun',
    projectBody1: 'Þetta repo er heill samþættingaverkefni fyrir Viking Bio 20 kornofninn: firmware, samskiptagreining, staðbundin runtime og sérstök browser-push app fyrir rekstrartilkynningar.',
    projectBody2: 'Fjallað er um heiðarlega rekstrarstýringu: haltu gögnum staðbundið, staðfestu tækið á mörkum og veittu áreiðanlega uppsetningarflæði án trausts á hýstum vöru eða cloud-backend.',
    footerBrand: 'Viking Bio Integration',
    footerGitHub: 'GitHub',
    widget: {
      setup: 'Staðbundin uppsetning',
      bridge: 'Brú',
      online: 'Ánetin',
      telemetry: 'Telemetría',
      signed: 'Undirrituð',
      config: 'Stilling',
      ready: 'Tilbúin',
      wifi: 'Wi‑Fi',
      stable: 'Stöðug',
      fan: 'Viftur',
      flame: 'Logi',
      healthy: 'Heilbrigð',
      state: 'Ástand',
      idle: 'Óvirkt',
    },
  },
} as const;
