#!/usr/bin/env python3
"""Convert web source files to C string literals for embedding in Pico W firmware.

Usage:
    gen_web_content.py OUTPUT_FILE file1.html VAR1 [file2.js VAR2 ...]
"""

import sys


def file_to_c_string(filepath, varname):
    """Read a file and return a C static const char[] string literal definition."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    lines = [f"static const char {varname}[] ="]
    for line in content.splitlines():
        escaped = line.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'"{escaped}\\n"')
    lines.append(";")
    return '\n'.join(lines) + '\n'


def main():
    if len(sys.argv) < 4 or (len(sys.argv) - 2) % 2 != 0:
        print(
            f"Usage: {sys.argv[0]} OUTPUT_FILE file1 VAR1 [file2 VAR2 ...]",
            file=sys.stderr,
        )
        sys.exit(1)

    output_file = sys.argv[1]
    pairs = [(sys.argv[i], sys.argv[i + 1]) for i in range(2, len(sys.argv), 2)]

    sections = [
        "/* Auto-generated from web source files. Do not edit directly. */",
        "/* Re-generated by cmake/gen_web_content.py during build. */",
        "#pragma once",
        "",
    ]

    for filepath, varname in pairs:
        sections.append(file_to_c_string(filepath, varname))

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sections))


if __name__ == '__main__':
    main()
